project:
  type: website
  output-dir: docs

website:
  title: "Yago Ramalho"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: portfolio.qmd
        text: Portfólio

format:
  html:
    theme: 
      light: minty
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full



