---
title: "Um pouco sobre mim"
---
Sempre me vi como uma pessoa de muitos interesses particulares: de literatura a matemática pura, tomo por princípio que não posso afirmar se gosto ou não de determinado assunto se nunca tentei estudá-lo ou pelo menos apreciar o que tem a oferecer.

Evidentemente, a curiosidade pela realidade ao meu redor exigiu, com o passar dos anos, disciplina e seletividade. A busca por alguma forma de conciliar tudo isso se traduziu no estudo de metodologias que me permitissem absorver um pouquinho de cada tema, justificando assim uma formação que contemplasse muitas possibilidades de interseção das diferentes áreas de conhecimento (economia), com uma ênfase que me possibilitasse transitar entre problemáticas diversas (estatística). 

Gosto de me descrever como alguém que aprecia encontrar formas de resolver problemas — me fascina na medida em que enxergo nas áreas de dados a possibilidade de transformar a curiosidade teórica e intelectual em algo tangível e com impacto. 

Enquanto economista, minha formação está intrinsecamente ligada à pesquisa: fui pesquisador Jr. durante o Ensino Médio (em Psicologia comportamental), e posteriormente desenvolvi pesquisas em econometria de séries temporais (onde estudei a interrelação entre séries financeiras no contexto de crises) e dados em painel (avaliei as correlações entre despesas públicas por função e produtividade nos estados brasileiros), ambas utilizando R. 

Ainda na graduação, participei de grupos de estudo e pesquisa em econometria e políticas públicas, além de ter sido membro bolsista do PET - Economia. No lado mais apaixonado da experiência universitária, também estudei meia dúzia de idiomas, sendo fluente em inglês mas completamente capaz de ler e traduzir francês e espanhol, com alguma experiência em outros. Se me perguntassem o que considero ser meu “dom”, sem dúvidas diria linguagens: gosto de ler e escrever tanto quanto de revisar e traduzir.

Profissionalmente, fui estagiário do Núcleo de Avaliação de Tendências e Riscos (NATR), no Tribunal de Contas (TCEES) por dois anos. Participei de atividades tradicionais como redação de boletins, coleta de dados, elaboração de painéis e gráficos, etc. Com o tempo, me tornei mais ativo nos projetos internos do núcleo, que incluíam elaboração de indicadores, elaboração de notas técnicas, além de auxiliar na inclusão de novos membros. 

Acredito na troca: no momento busco um ambiente que me permita crescer dentro de tudo isso que venho construindo, na mesma medida em que posso oferecer um pouco daquilo que aprendi e acredito: disciplina, rigor, e um excesso de curiosidade.
